-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 18:48:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`html_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`html_tags` (
  `id_html_tags` INT NOT NULL,
  `tag-name` VARCHAR(45) NULL,
  `isEven` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id_html_tags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id_players` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_players`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`css_attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`css_attributes` (
  `id_css` INT UNSIGNED NOT NULL,
  `attribute` VARCHAR(45) NULL,
  PRIMARY KEY (`id_css`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types` (
  `id-types` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id-types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`css_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`css_values` (
  `id_css_values` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `types_id-types` INT NOT NULL,
  PRIMARY KEY (`id_css_values`),
  INDEX `fk_css_values_types1_idx` (`types_id-types` ASC) VISIBLE,
  CONSTRAINT `fk_css_values_types1`
    FOREIGN KEY (`types_id-types`)
    REFERENCES `mydb`.`types` (`id-types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`html_tag_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`html_tag_values` (
  `id_html_tag_value` INT UNSIGNED NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_html_tag_value`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`css`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`css` (
  `id_css` INT NOT NULL,
  `attrbiute_id` INT NOT NULL,
  `value_id` INT NOT NULL,
  PRIMARY KEY (`id_css`),
  INDEX `fk_css_css_attributes_idx` (`attrbiute_id` ASC) VISIBLE,
  INDEX `fk_css_css_values1_idx` (`value_id` ASC) VISIBLE,
  CONSTRAINT `fk_css_css_attributes`
    FOREIGN KEY (`attrbiute_id`)
    REFERENCES `mydb`.`css_attributes` (`id_css`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_css_css_values1`
    FOREIGN KEY (`value_id`)
    REFERENCES `mydb`.`css_values` (`id_css_values`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`html_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`html_components` (
  `id_html_components` INT NOT NULL AUTO_INCREMENT,
  `html_tag` INT NOT NULL,
  `css` INT NOT NULL,
  `tag_value` INT NOT NULL,
  PRIMARY KEY (`id_html_components`),
  INDEX `fk_html_components_html_tags1_idx` (`html_tag` ASC) VISIBLE,
  INDEX `fk_html_components_css1_idx` (`css` ASC) VISIBLE,
  INDEX `fk_html_components_html_tag_values1_idx` (`tag_value` ASC) VISIBLE,
  CONSTRAINT `fk_html_components_html_tags1`
    FOREIGN KEY (`html_tag`)
    REFERENCES `mydb`.`html_tags` (`id_html_tags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_html_components_css1`
    FOREIGN KEY (`css`)
    REFERENCES `mydb`.`css` (`id_css`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_html_components_html_tag_values1`
    FOREIGN KEY (`tag_value`)
    REFERENCES `mydb`.`html_tag_values` (`id_html_tag_value`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`html_components_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`html_components_name` (
  `id_html_components_name` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_html_components_name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
